# tackling goal0, goal_0.78
exp_name: "VarPE_goal0_0.78"
torch_deterministic: true
cuda: true
track: true
wandb_project_name: "simple-gvf-evaluations"
wandb_entity: "jainarus"
wandb_group: "try_var"
capture_video: false
save_model: false
upload_model: false
hf_entity: ""
run_save_loc: "/home/mila/j/jainarus/scratch/clean-rl/try_var_ours"

env_id: "DiscreteActionsPendulumEnv-v0"
goal_position: 0.0 # don't change this
goal_positions_pe: [0.0, 0.78]
total_timesteps: 80000
batch_size: 64
gamma: 0.99
tau: 1.0
target_network_frequency: 100
start_e: 0.
end_e: 0.0
exploration_fraction: 0.01
start_var_lambd: 1.0
end_var_lambd: 0.0
learning_starts: 200
train_frequency: 4
q_type_loss: 0
var_type_loss: 1
#don't change this
variance_train_frequency: 2
eval_frequency: 100
checkpoint_frequency: 5000
eval_episodes: 5

# this is fixed, don't change
checkpoint_number: 5000
