# puddle [goal_0, goal_1]
exp_name: "goal_0"
puddle_goal_type: 0
seed: 1
torch_deterministic: true
cuda: true
track: true
wandb_project_name: "simple-gvf-evaluations"
wandb_entity: "jainarus"
wandb_group: "puddle-single-reward-dqn-non-greedy-1"
capture_video: false
save_model: true
upload_model: false
hf_entity: ""
run_save_loc: "/home/mila/j/jainarus/scratch/clean-rl/puddle/single-reward-dqn"

env_id: "PuddleMultiGoals-v0"
total_timesteps: 30000
learning_rate: !!float 2.5e-4
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 100
batch_size: 64
start_e: 0.8
end_e: 0.25
exploration_fraction: 0.01
learning_starts: 100
train_frequency: 4
eval_frequency: 200
checkpoint_frequency: 250
eval_episodes: 20

checkpoint_number: 4500
