# tackling goal0, goal_0.78
#exp_name: "PE_goal0_0.78"
exp_name: "Var_puddle_random_states_more_time"
puddle_goal_type: 2
torch_deterministic: true
cuda: true
track: true
wandb_project_name: "simple-gvf-evaluations"
wandb_entity: "jainarus"
wandb_group: "Var_PE_puddle_random_states_more_time"
capture_video: false
save_model: false
upload_model: false
hf_entity: ""
run_save_loc: "/home/mila/j/jainarus/scratch/clean-rl/puddle/Var_PE/random_states"

#env_id: "DiscreteActionsPendulumEnv-v0"
env_id: "PuddleMultiGoals-v0"
#learning_rate: !!float 1e-4
batch_size: 64
total_timesteps: 800000
#buffer_size: 5000
gamma: 0.99
#tau: 1.0
#target_network_frequency: 100
start_e: 0.
end_e: 0.0
exploration_fraction: 0.01
start_var_lambd: 1.0
end_var_lambd: 0.0
learning_starts: 500
#train_frequency: 4
#q_type_loss: 0
#var_type_loss: 1
beh_plot_frequency: 100000
compute_mse_for_random_states: 1
var_lambd_fraction: 0.002

# var next target type
type_next_target_val: 0

#don't change this
#variance_train_frequency: 2
eval_frequency: 500
checkpoint_frequency: 100000
eval_episodes: 10

# this is fixed, don't change
checkpoint_number: 4500
